before_install:
  - "cpanm Module::Install::ReadmeFromPod Module::Install::Any::Moose Test::Requires Module::Install::Repository"

env:
  - ANY_MOOSE=Moose
  - ANY_MOOSE=Mouse

language: perl
perl:
  - "5.14"
  - "5.16"
